<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robcraft_maze_demo</name>
  <version>0.1.0</version>
  <description>RobCraft Maze Demo package</description>
  <maintainer email="mgons@unileon.es">Miguel Ángel González Santamarta</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>navigation2</depend>
  <depend>nav2_bringup</depend>
  <depend>nav2_common</depend>
  <depend>dwb_core</depend>
  <depend>slam_toolbox</depend>
  <depend>rtabmap_slam</depend>
  <depend>rtabmap_odom</depend>
  <depend>rtabmap_viz</depend>
  <depend>robot_localization</depend>
  <depend>rclcpp_components</depend>
  <depend>rviz2</depend>
  <depend>robcraft</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>