<?xml version="1.0"?>
<package format="3">
  <name>robcraft_cli</name>
  <version>1.0.0</version>
  <description>ROS 2 CLI extensions for RobCraft.</description>
  <maintainer email="mgons@unileon.es">Miguel Ángel González Santamarta</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>ros2cli</exec_depend>
  <exec_depend>robcraft</exec_depend>

  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
